const buses = [
    { id: 1, operator: "SwiftLine Express", vehicle: "A/C Sleeper (2+1)", tags: ["Free Snacks", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 512, depart: "22:15", arrive: "05:35", duration: "7h 20m", seatsTotal: 36, singleSeats: 8, price: 459, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 699, cutoffPrice: 459, cta: "View seats" },
    { id: 2, operator: "BluePeak Travels", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["On Time", "Wi‑Fi"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 388, depart: "23:05", arrive: "06:10", duration: "7h 05m", seatsTotal: 41, singleSeats: 9, price: 499, currency: "INR", priceNote: "", deal: "", originalPrice: 499, cutoffPrice: 499, cta: "View seats" },
    { id: 3, operator: "RedArrow Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.6, reviewsCount: 640, depart: "21:40", arrive: "04:55", duration: "7h 15m", seatsTotal: 40, singleSeats: 7, price: 479, currency: "INR", priceNote: "", deal: "Exclusive 12% OFF", originalPrice: 545, cutoffPrice: 479, cta: "View seats" },
    { id: 4, operator: "CityNest Buslines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Live Tracking"], tag2: "Exclusive discounts available for women passengers", rating: 4.1, reviewsCount: 271, depart: "00:10", arrive: "06:45", duration: "6h 35m", seatsTotal: 32, singleSeats: 6, price: 369, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 5, operator: "Northern Trailways", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Minimum 10% off on return ticket", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.7, reviewsCount: 728, depart: "23:25", arrive: "06:05", duration: "6h 40m", seatsTotal: 34, singleSeats: 5, price: 539, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 613, cutoffPrice: 539, cta: "View seats" },
    { id: 6, operator: "GreenLeaf Mobility", vehicle: "A/C Seater (2+2)", tags: ["On Time", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.0, reviewsCount: 233, depart: "20:55", arrive: "03:30", duration: "6h 35m", seatsTotal: 28, singleSeats: 3, price: 329, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 329, cutoffPrice: 329, cta: "View seats" },
    { id: 7, operator: "MetroHive Buses", vehicle: "A/C Sleeper (2+1)", tags: ["Free Snacks", "Toilet"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 415, depart: "22:50", arrive: "06:00", duration: "7h 10m", seatsTotal: 38, singleSeats: 8, price: 469, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 521, cutoffPrice: 469, cta: "View seats" },
    { id: 8, operator: "Sunrise Voyagers", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 502, depart: "23:40", arrive: "06:50", duration: "7h 10m", seatsTotal: 42, singleSeats: 10, price: 519, currency: "INR", priceNote: "", deal: "", originalPrice: 519, cutoffPrice: 519, cta: "View seats" },
    { id: 9, operator: "RapidGo Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "Live Tracking"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 367, depart: "21:15", arrive: "04:45", duration: "7h 30m", seatsTotal: 35, singleSeats: 6, price: 399, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 399, cutoffPrice: 399, cta: "View seats" },
    { id: 10, operator: "CoastalRide Tours", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.4, reviewsCount: 451, depart: "00:05", arrive: "06:20", duration: "6h 15m", seatsTotal: 33, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 399, cutoffPrice: 359, cta: "View seats" },
    { id: 11, operator: "Everest Roadways", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Toilet", "Free Snacks"], tag2: "Minimum 10% off on return ticket", rating: 4.6, reviewsCount: 592, depart: "22:30", arrive: "05:25", duration: "6h 55m", seatsTotal: 30, singleSeats: 4, price: 449, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 449, cutoffPrice: 449, cta: "View seats" },
    { id: 12, operator: "UrbanJet Transit", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 342, depart: "23:55", arrive: "06:35", duration: "6h 40m", seatsTotal: 37, singleSeats: 9, price: 489, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 556, cutoffPrice: 489, cta: "View seats" },
    { id: 13, operator: "Granite Wheels", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["On Time", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 286, depart: "21:05", arrive: "04:30", duration: "7h 25m", seatsTotal: 29, singleSeats: 4, price: 339, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 339, cutoffPrice: 339, cta: "View seats" },
    { id: 14, operator: "SkyTrail Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Toilet"], tag2: "Exclusive discounts available for women passengers", rating: 4.7, reviewsCount: 734, depart: "22:10", arrive: "05:30", duration: "7h 20m", seatsTotal: 43, singleSeats: 10, price: 549, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 624, cutoffPrice: 549, cta: "View seats" },
    { id: 15, operator: "SilverLeaf Lines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Free Snacks"], tag2: "Minimum 10% off on return ticket", rating: 4.0, reviewsCount: 219, depart: "23:20", arrive: "06:15", duration: "6h 55m", seatsTotal: 36, singleSeats: 7, price: 439, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 439, cutoffPrice: 439, cta: "View seats" },
    { id: 16, operator: "StarBridge Mobility", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 372, depart: "20:40", arrive: "03:55", duration: "7h 15m", seatsTotal: 27, singleSeats: 2, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 17, operator: "CoralPath Travels", vehicle: "A/C Sleeper (2+1)", tags: ["On Time", "Live Tracking"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 506, depart: "22:05", arrive: "05:35", duration: "7h 30m", seatsTotal: 39, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 18, operator: "AmberRoad Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Toilet"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 401, depart: "23:45", arrive: "06:50", duration: "7h 05m", seatsTotal: 40, singleSeats: 8, price: 529, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 19, operator: "RiverStone Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Blankets"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 308, depart: "21:25", arrive: "04:50", duration: "7h 25m", seatsTotal: 31, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 20, operator: "PearlGate Buses", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 618, depart: "22:55", arrive: "05:40", duration: "6h 45m", seatsTotal: 33, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 533, cutoffPrice: 469, cta: "View seats" },
    { id: 21, operator: "Magneto Travels", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 355, depart: "22:35", arrive: "05:50", duration: "7h 15m", seatsTotal: 35, singleSeats: 8, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 22, operator: "NeonTrail Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Live Tracking"], tag2: "Exclusive discounts available for women passengers", rating: 4.4, reviewsCount: 493, depart: "23:15", arrive: "06:10", duration: "6h 55m", seatsTotal: 41, singleSeats: 10, price: 519, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 577, cutoffPrice: 519, cta: "View seats" },
    { id: 23, operator: "CedarRoute Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 228, depart: "21:50", arrive: "05:05", duration: "7h 15m", seatsTotal: 30, singleSeats: 4, price: 349, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 349, cutoffPrice: 349, cta: "View seats" },
    { id: 24, operator: "AquaJet Mobility", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Free Snacks"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 538, depart: "00:20", arrive: "06:40", duration: "6h 20m", seatsTotal: 38, singleSeats: 7, price: 439, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 500, cutoffPrice: 439, cta: "View seats" },
    { id: 25, operator: "HarborLine Coaches", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Charging Point", "On Time"], tag2: "Exclusive discounts available for women passengers", rating: 4.1, reviewsCount: 316, depart: "22:20", arrive: "05:30", duration: "7h 10m", seatsTotal: 29, singleSeats: 3, price: 339, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 339, cutoffPrice: 339, cta: "View seats" },
    { id: 26, operator: "Aurora Wheels", vehicle: "A/C Sleeper (2+1)", tags: ["Blankets", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 421, depart: "23:30", arrive: "06:25", duration: "6h 55m", seatsTotal: 37, singleSeats: 9, price: 489, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 544, cutoffPrice: 489, cta: "View seats" },
    { id: 27, operator: "LionGate Express", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Live Tracking", "Toilet"], tag2: "Exclusive discounts available for women passengers", rating: 4.5, reviewsCount: 560, depart: "21:30", arrive: "04:55", duration: "7h 25m", seatsTotal: 39, singleSeats: 8, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 28, operator: "Mirage Movers", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 362, depart: "22:45", arrive: "05:50", duration: "7h 05m", seatsTotal: 34, singleSeats: 6, price: 419, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 419, cutoffPrice: 419, cta: "View seats" },
    { id: 29, operator: "MoonRail Transit", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "On Time"], tag2: "Exclusive discounts available for women passengers", rating: 4.4, reviewsCount: 478, depart: "23:05", arrive: "06:00", duration: "6h 55m", seatsTotal: 36, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 30, operator: "ThunderRoad Lines", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 209, depart: "20:30", arrive: "03:45", duration: "7h 15m", seatsTotal: 26, singleSeats: 2, price: 319, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 319, cutoffPrice: 319, cta: "View seats" },
    { id: 31, operator: "OliveWay Bus Co.", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 395, depart: "22:25", arrive: "05:40", duration: "7h 15m", seatsTotal: 33, singleSeats: 8, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 32, operator: "CopperTrail Mobility", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 602, depart: "23:50", arrive: "06:30", duration: "6h 40m", seatsTotal: 41, singleSeats: 9, price: 539, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 599, cutoffPrice: 539, cta: "View seats" },
    { id: 33, operator: "CrystalLine Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 301, depart: "21:10", arrive: "04:35", duration: "7h 25m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 34, operator: "VelvetRide Transit", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.5, reviewsCount: 547, depart: "22:40", arrive: "05:35", duration: "6h 55m", seatsTotal: 31, singleSeats: 4, price: 449, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 510, cutoffPrice: 449, cta: "View seats" },
    { id: 35, operator: "JadePeak Lines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 354, depart: "23:35", arrive: "06:50", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 36, operator: "Cobalt Route", vehicle: "A/C Seater (2+2)", tags: ["Free Snacks", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 214, depart: "20:20", arrive: "03:50", duration: "7h 30m", seatsTotal: 25, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 37, operator: "RubyRoad Express", vehicle: "A/C Sleeper (2+1)", tags: ["Toilet", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 468, depart: "22:05", arrive: "05:25", duration: "7h 20m", seatsTotal: 35, singleSeats: 8, price: 479, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 479, cutoffPrice: 479, cta: "View seats" },
    { id: 38, operator: "MapleWing Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 376, depart: "23:20", arrive: "06:05", duration: "6h 45m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 566, cutoffPrice: 509, cta: "View seats" },
    { id: 39, operator: "CanyonEdge Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 294, depart: "21:55", arrive: "05:10", duration: "7h 15m", seatsTotal: 31, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 40, operator: "PolarStar Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Charging Point", "On Time"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 621, depart: "22:50", arrive: "05:45", duration: "6h 55m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 521, cutoffPrice: 469, cta: "View seats" },
    { id: 41, operator: "SaffronGate Buses", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 409, depart: "23:45", arrive: "07:00", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 42, operator: "EchoLine Transit", vehicle: "A/C Seater (2+2)", tags: ["Free Snacks", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 236, depart: "20:45", arrive: "04:15", duration: "7h 30m", seatsTotal: 26, singleSeats: 3, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 43, operator: "Orchid Roadways", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "Live Tracking"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 521, depart: "22:35", arrive: "05:55", duration: "7h 20m", seatsTotal: 36, singleSeats: 8, price: 499, currency: "INR", priceNote: "Onwards", deal: "Women 12% OFF", originalPrice: 568, cutoffPrice: 499, cta: "View seats" },
    { id: 44, operator: "QuartzMove Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 364, depart: "23:30", arrive: "06:20", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 519, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 519, cutoffPrice: 519, cta: "View seats" },
    { id: 45, operator: "HazelTrack Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["On Time", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 289, depart: "21:20", arrive: "04:45", duration: "7h 25m", seatsTotal: 32, singleSeats: 5, price: 369, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 46, operator: "LotusSky Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 633, depart: "22:25", arrive: "05:15", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 522, cutoffPrice: 459, cta: "View seats" },
    { id: 47, operator: "CitrusTrail Tours", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 397, depart: "23:10", arrive: "06:25", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 48, operator: "IndigoPath Transit", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 241, depart: "20:10", arrive: "03:50", duration: "7h 40m", seatsTotal: 27, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 49, operator: "Topaz Lane Coaches", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 452, depart: "22:15", arrive: "05:30", duration: "7h 15m", seatsTotal: 35, singleSeats: 8, price: 479, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 533, cutoffPrice: 479, cta: "View seats" },
    { id: 50, operator: "CanyonLeaf Express", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 381, depart: "23:25", arrive: "06:15", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 51, operator: "NimbusRoad Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 298, depart: "21:45", arrive: "05:05", duration: "7h 20m", seatsTotal: 31, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 52, operator: "VistaRise Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.5, reviewsCount: 556, depart: "22:55", arrive: "05:45", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 53, operator: "OpalBridge Buses", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 346, depart: "23:40", arrive: "06:55", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 54, operator: "Marigold Movers", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 205, depart: "20:25", arrive: "03:55", duration: "7h 30m", seatsTotal: 25, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 55, operator: "FalconWay Coaches", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 463, depart: "22:05", arrive: "05:20", duration: "7h 15m", seatsTotal: 36, singleSeats: 8, price: 479, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 479, cutoffPrice: 479, cta: "View seats" },
    { id: 56, operator: "ArcticLine Transit", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 418, depart: "23:10", arrive: "06:00", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 529, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 57, operator: "MangoRoute Express", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 284, depart: "21:00", arrive: "04:25", duration: "7h 25m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 58, operator: "RoyalMint Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Minimum 10% off on return ticket"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 642, depart: "22:30", arrive: "05:20", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 59, operator: "Sapphire Roadways", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 403, depart: "23:55", arrive: "07:10", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 60, operator: "TerraNova Coaches", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 238, depart: "20:05", arrive: "03:45", duration: "7h 40m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 61, operator: "AuricRoad Lines", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 533, depart: "22:45", arrive: "06:05", duration: "7h 20m", seatsTotal: 35, singleSeats: 8, price: 499, currency: "INR", priceNote: "Onwards", deal: "Women 10% OFF", originalPrice: 555, cutoffPrice: 499, cta: "View seats" },
    { id: 62, operator: "MintyRide Transit", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 372, depart: "23:20", arrive: "06:10", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 63, operator: "PrismPath Buses", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 292, depart: "21:30", arrive: "04:55", duration: "7h 25m", seatsTotal: 31, singleSeats: 5, price: 369, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 64, operator: "GoldenWings Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 629, depart: "22:35", arrive: "05:25", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 65, operator: "MistyWay Coaches", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 351, depart: "23:05", arrive: "06:15", duration: "7h 10m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 66, operator: "CivicLane Transit", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 217, depart: "20:55", arrive: "04:30", duration: "7h 35m", seatsTotal: 26, singleSeats: 2, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 67, operator: "ZenithRide Express", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 472, depart: "22:20", arrive: "05:40", duration: "7h 20m", seatsTotal: 36, singleSeats: 8, price: 489, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 489, cutoffPrice: 489, cta: "View seats" },
    { id: 68, operator: "AzureGate Lines", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 419, depart: "23:30", arrive: "06:20", duration: "6h 50m", seatsTotal: 41, singleSeats: 9, price: 529, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 69, operator: "ForestEdge Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 287, depart: "21:10", arrive: "04:40", duration: "7h 30m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 70, operator: "HarborWind Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 640, depart: "22:10", arrive: "05:00", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "Onwards", deal: "Women 12% OFF", originalPrice: 522, cutoffPrice: 459, cta: "View seats" },
    { id: 71, operator: "CedarBeam Lines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 405, depart: "23:40", arrive: "06:55", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 72, operator: "PineWave Transit", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 243, depart: "20:35", arrive: "04:10", duration: "7h 35m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 73, operator: "CrimsonJet Travels", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 540, depart: "22:30", arrive: "05:50", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 499, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 555, cutoffPrice: 499, cta: "View seats" },
    { id: 74, operator: "FlintRock Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 379, depart: "23:05", arrive: "06:00", duration: "6h 55m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 75, operator: "CrownHill Mobility", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 296, depart: "21:25", arrive: "04:55", duration: "7h 30m", seatsTotal: 31, singleSeats: 5, price: 369, currency: "INR", priceNote: "", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 76, operator: "GraniteGlow Lines", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 651, depart: "22:55", arrive: "05:45", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 77, operator: "CobaltWing Express", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 349, depart: "23:25", arrive: "06:40", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 78, operator: "IvoryLane Transit", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 223, depart: "20:15", arrive: "03:45", duration: "7h 30m", seatsTotal: 26, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 79, operator: "PlatinumPath Coaches", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 466, depart: "22:00", arrive: "05:20", duration: "7h 20m", seatsTotal: 35, singleSeats: 8, price: 479, currency: "INR", priceNote: "", deal: "", originalPrice: 479, cutoffPrice: 479, cta: "View seats" },
    { id: 80, operator: "EmeraldRide Mobility", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 422, depart: "23:15", arrive: "06:05", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 529, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 81, operator: "CedarStone Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 291, depart: "21:40", arrive: "05:10", duration: "7h 30m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 82, operator: "LotusBeam Transit", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 638, depart: "22:20", arrive: "05:10", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 83, operator: "OceanMint Coaches", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 407, depart: "23:50", arrive: "07:05", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 84, operator: "RiverMint Mobility", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 246, depart: "20:25", arrive: "04:00", duration: "7h 35m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 85, operator: "MarbleJet Express", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 544, depart: "22:40", arrive: "06:00", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 499, currency: "INR", priceNote: "", deal: "Women 10% OFF", originalPrice: 555, cutoffPrice: 499, cta: "View seats" },
    { id: 86, operator: "AmberSky Transit", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 383, depart: "23:35", arrive: "06:25", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 87, operator: "PineStone Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 295, depart: "21:05", arrive: "04:30", duration: "7h 25m", seatsTotal: 31, singleSeats: 5, price: 369, currency: "INR", priceNote: "", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 88, operator: "VelvetMint Lines", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 646, depart: "22:45", arrive: "05:35", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 89, operator: "HarborPeak Mobility", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 353, depart: "23:10", arrive: "06:25", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 90, operator: "CanyonWave Transit", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 227, depart: "20:50", arrive: "04:20", duration: "7h 30m", seatsTotal: 26, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 91, operator: "MosaicRoute Coaches", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 470, depart: "22:55", arrive: "06:15", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 489, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 489, cutoffPrice: 489, cta: "View seats" },
    { id: 92, operator: "SilverMint Lines", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 426, depart: "23:45", arrive: "06:35", duration: "6h 50m", seatsTotal: 41, singleSeats: 9, price: 529, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 93, operator: "OliveJet Mobility", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 299, depart: "21:20", arrive: "04:50", duration: "7h 30m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 94, operator: "CedarWave Transit", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 652, depart: "22:15", arrive: "05:05", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 95, operator: "MagentaRoad Lines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 411, depart: "23:30", arrive: "06:45", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 96, operator: "UrbanCrest Coaches", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 248, depart: "20:30", arrive: "04:00", duration: "7h 30m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 97, operator: "RusticRide Express", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 548, depart: "22:25", arrive: "05:45", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 499, currency: "INR", priceNote: "Onwards", deal: "Women 12% OFF", originalPrice: 568, cutoffPrice: 499, cta: "View seats" },
    { id: 98, operator: "TopazMint Mobility", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 385, depart: "23:05", arrive: "05:55", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 99, operator: "MeadowLine Transit", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 303, depart: "21:35", arrive: "05:05", duration: "7h 30m", seatsTotal: 31, singleSeats: 5, price: 369, currency: "INR", priceNote: "", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 100, operator: "CrescentPath Lines", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 660, depart: "22:05", arrive: "04:55", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 101, operator: "MintWave Coaches", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 347, depart: "23:20", arrive: "06:35", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 102, operator: "HarborCrest Mobility", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 229, depart: "20:40", arrive: "04:10", duration: "7h 30m", seatsTotal: 26, singleSeats: 2, price: 309, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 103, operator: "MarinaJet Express", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 474, depart: "22:50", arrive: "06:10", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 489, currency: "INR", priceNote: "", deal: "", originalPrice: 489, cutoffPrice: 489, cta: "View seats" },
    { id: 104, operator: "PrairieMint Lines", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 430, depart: "23:40", arrive: "06:30", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 529, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 105, operator: "CrystalWave Transit", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 305, depart: "21:15", arrive: "04:45", duration: "7h 30m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 106, operator: "SeaBreeze Mobility", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 664, depart: "22:25", arrive: "05:15", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 107, operator: "GraniteCrest Lines", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 413, depart: "23:55", arrive: "07:10", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 108, operator: "CloverRoute Coaches", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 252, depart: "20:20", arrive: "03:55", duration: "7h 35m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 355, cutoffPrice: 319, cta: "View seats" },
    { id: 109, operator: "NimbusTrail Mobility", vehicle: "A/C Sleeper (2+1)", tags: ["Wi‑Fi", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 552, depart: "22:35", arrive: "05:55", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 499, currency: "INR", priceNote: "", deal: "Women 10% OFF", originalPrice: 555, cutoffPrice: 499, cta: "View seats" },
    { id: 110, operator: "IvoryPeak Transit", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 387, depart: "23:25", arrive: "06:15", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 509, currency: "INR", priceNote: "", deal: "", originalPrice: 509, cutoffPrice: 509, cta: "View seats" },
    { id: 111, operator: "RiverGlow Lines", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Toilet", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 307, depart: "21:30", arrive: "05:00", duration: "7h 30m", seatsTotal: 31, singleSeats: 5, price: 369, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 369, cutoffPrice: 369, cta: "View seats" },
    { id: 112, operator: "CoralMint Coaches", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["On Time", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 668, depart: "22:40", arrive: "05:30", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 469, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 534, cutoffPrice: 469, cta: "View seats" },
    { id: 113, operator: "OliveBridge Mobility", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 355, depart: "23:10", arrive: "06:25", duration: "7h 15m", seatsTotal: 37, singleSeats: 7, price: 459, currency: "INR", priceNote: "", deal: "", originalPrice: 459, cutoffPrice: 459, cta: "View seats" },
    { id: 114, operator: "CrestLane Transit", vehicle: "A/C Seater (2+2)", tags: ["Minimum 10% off on return ticket", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 231, depart: "20:10", arrive: "03:40", duration: "7h 30m", seatsTotal: 26, singleSeats: 2, price: 309, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 343, cutoffPrice: 309, cta: "View seats" },
    { id: 115, operator: "HarborStone Express", vehicle: "A/C Sleeper (2+1)", tags: ["Live Tracking", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 478, depart: "22:15", arrive: "05:35", duration: "7h 20m", seatsTotal: 36, singleSeats: 9, price: 489, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 489, cutoffPrice: 489, cta: "View seats" },
    { id: 116, operator: "AzureMint Lines", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Toilet", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 434, depart: "23:05", arrive: "05:55", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 529, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 588, cutoffPrice: 529, cta: "View seats" },
    { id: 117, operator: "ValleyCrest Mobility", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Charging Point", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 309, depart: "21:05", arrive: "04:35", duration: "7h 30m", seatsTotal: 32, singleSeats: 5, price: 359, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 359, cutoffPrice: 359, cta: "View seats" },
    { id: 118, operator: "PrairieGate Transit", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Free Snacks", "Blankets"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 672, depart: "22:30", arrive: "05:20", duration: "6h 50m", seatsTotal: 33, singleSeats: 4, price: 459, currency: "INR", priceNote: "", deal: "Exclusive 10% OFF", originalPrice: 510, cutoffPrice: 459, cta: "View seats" },
    { id: 119, operator: "CrystalMint Coaches", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 415, depart: "23:20", arrive: "06:35", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 469, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 469, cutoffPrice: 469, cta: "View seats" },
    { id: 120, operator: "UrbanMint Lines", vehicle: "A/C Seater (2+2)", tags: ["Charging Point", "Water Bottle", "snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 256, depart: "20:55", arrive: "04:25", duration: "7h 30m", seatsTotal: 27, singleSeats: 3, price: 319, currency: "INR", priceNote: "", deal: "", originalPrice: 319, cutoffPrice: 319, cta: "View seats" },
    { id: 121, operator: "Primo Star Travels", vehicle: "A/C Sleeper (2+1)", tags: ["Free date change", "Toilet"], tag2: "Exclusive discounts available for women passengers", rating: 4.5, reviewsCount: 188, depart: "22:08", arrive: "04:30", duration: "6h 22m", seatsTotal: 27, singleSeats: 8, price: 679, currency: "INR", priceNote: "Onwards", deal: "Women 10% OFF", originalPrice: 755, cutoffPrice: 679, cta: "View seats" },
    { id: 122, operator: "ZingGo Plus", vehicle: "A/C Seater / Sleeper (2+1)", tags: ["Min. 12.5% OFF on 3 or more seats", "New Bus"], tag2: "Minimum 10% off on return ticket", rating: 4.2, reviewsCount: 452, depart: "23:10", arrive: "05:55", duration: "6h 45m", seatsTotal: 33, singleSeats: 9, price: 419, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 476, cutoffPrice: 419, cta: "View seats" },
    { id: 123, operator: "MetroSwift Lines", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.3, reviewsCount: 390, depart: "21:40", arrive: "04:50", duration: "7h 10m", seatsTotal: 39, singleSeats: 8, price: 505, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 505, cutoffPrice: 505, cta: "View seats" },
    { id: 124, operator: "CityLink Express", vehicle: "A/C Seater (2+2)", tags: ["Live Tracking", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 278, depart: "20:20", arrive: "03:55", duration: "7h 35m", seatsTotal: 28, singleSeats: 3, price: 329, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 366, cutoffPrice: 329, cta: "View seats" },
    { id: 125, operator: "GreenRoute Coaches", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["On Time", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 244, depart: "22:05", arrive: "05:25", duration: "7h 20m", seatsTotal: 34, singleSeats: 6, price: 445, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 445, cutoffPrice: 445, cta: "View seats" },
    { id: 126, operator: "Sunset Movers", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Charging Point"], tag2: "Minimum 10% off on return ticket", rating: 4.4, reviewsCount: 332, depart: "23:30", arrive: "06:40", duration: "7h 10m", seatsTotal: 36, singleSeats: 7, price: 462, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 513, cutoffPrice: 462, cta: "View seats" },
    { id: 127, operator: "AeroCity Transit", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Blankets", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 612, depart: "22:28", arrive: "05:15", duration: "6h 47m", seatsTotal: 33, singleSeats: 4, price: 468, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 532, cutoffPrice: 468, cta: "View seats" },
    { id: 128, operator: "GoldenArrow Lines", vehicle: "A/C Sleeper (2+1)", tags: ["Toilet", "Wi‑Fi"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 410, depart: "21:55", arrive: "05:05", duration: "7h 10m", seatsTotal: 35, singleSeats: 8, price: 488, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 488, cutoffPrice: 488, cta: "View seats" },
    { id: 129, operator: "BlueSky Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Water Bottle", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 372, depart: "23:12", arrive: "06:02", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 512, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 569, cutoffPrice: 512, cta: "View seats" },
    { id: 130, operator: "RapidTrail Express", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["On Time", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 300, depart: "21:18", arrive: "04:46", duration: "7h 28m", seatsTotal: 32, singleSeats: 5, price: 361, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 361, cutoffPrice: 361, cta: "View seats" },
    { id: 131, operator: "CoralLeaf Mobility", vehicle: "A/C Seater (2+2)", tags: ["Free Snacks", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.0, reviewsCount: 210, depart: "20:05", arrive: "03:45", duration: "7h 40m", seatsTotal: 26, singleSeats: 2, price: 311, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 345, cutoffPrice: 311, cta: "View seats" },
    { id: 132, operator: "RubyLine Travels", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Live Tracking"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 365, depart: "22:58", arrive: "06:10", duration: "7h 12m", seatsTotal: 37, singleSeats: 7, price: 471, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 471, cutoffPrice: 471, cta: "View seats" },
    { id: 133, operator: "PearlStone Coaches", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Water Bottle"], tag2: "Exclusive discounts available for women passengers", rating: 4.4, reviewsCount: 520, depart: "23:48", arrive: "06:38", duration: "6h 50m", seatsTotal: 41, singleSeats: 10, price: 538, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 598, cutoffPrice: 538, cta: "View seats" },
    { id: 134, operator: "EmeraldCity Lines", vehicle: "A/C Sleeper (2+1)", tags: ["Toilet", "On Time"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 560, depart: "22:12", arrive: "05:32", duration: "7h 20m", seatsTotal: 36, singleSeats: 8, price: 497, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 497, cutoffPrice: 497, cta: "View seats" },
    { id: 135, operator: "SilverHorizon", vehicle: "Electric A/C Semi Sleeper (2+2)", tags: ["Blankets", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.6, reviewsCount: 640, depart: "22:34", arrive: "05:24", duration: "6h 50m", seatsTotal: 34, singleSeats: 4, price: 471, currency: "INR", priceNote: "Onwards", deal: "Exclusive 12% OFF", originalPrice: 535, cutoffPrice: 471, cta: "View seats" },
    { id: 136, operator: "AlphaRide Express", vehicle: "VE A/C Seater / Sleeper (2+1)", tags: ["Water Bottle", "Free Snacks"], tag2: "Minimum 10% off on return ticket", rating: 4.1, reviewsCount: 312, depart: "21:28", arrive: "04:58", duration: "7h 30m", seatsTotal: 31, singleSeats: 5, price: 357, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 357, cutoffPrice: 357, cta: "View seats" },
    { id: 137, operator: "NovaJet Coaches", vehicle: "A/C Seater (2+2)", tags: ["Live Tracking", "Charging Point"], tag2: "Exclusive discounts available for women passengers", rating: 4.2, reviewsCount: 338, depart: "20:18", arrive: "03:55", duration: "7h 37m", seatsTotal: 28, singleSeats: 3, price: 327, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 364, cutoffPrice: 327, cta: "View seats" },
    { id: 138, operator: "HarborVista Mobility", vehicle: "Bharat Benz A/C Seater / Sleeper (2+1)", tags: ["New Bus", "Toilet"], tag2: "Minimum 10% off on return ticket", rating: 4.3, reviewsCount: 402, depart: "23:22", arrive: "06:37", duration: "7h 15m", seatsTotal: 38, singleSeats: 7, price: 463, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 463, cutoffPrice: 463, cta: "View seats" },
    { id: 139, operator: "SkyBridge Transit", vehicle: "Electric A/C Seater/Sleeper (2+1)", tags: ["Wi‑Fi", "Free Snacks"], tag2: "Exclusive discounts available for women passengers", rating: 4.4, reviewsCount: 518, depart: "23:18", arrive: "06:08", duration: "6h 50m", seatsTotal: 40, singleSeats: 9, price: 517, currency: "INR", priceNote: "Onwards", deal: "Exclusive 10% OFF", originalPrice: 575, cutoffPrice: 517, cta: "View seats" },
    { id: 140, operator: "AuroraGate Lines", vehicle: "A/C Sleeper (2+1)", tags: ["On Time", "Water Bottle"], tag2: "Minimum 10% off on return ticket", rating: 4.5, reviewsCount: 548, depart: "22:04", arrive: "05:24", duration: "7h 20m", seatsTotal: 36, singleSeats: 8, price: 495, currency: "INR", priceNote: "Onwards", deal: "", originalPrice: 495, cutoffPrice: 495, cta: "View seats" }
];



var product = '';

for (var i = 0; i < buses.length; i++) {
    const tagChips = (buses[i].tags || [])
        .map(t => `<span class="chip muted">${t}</span>`)
        .join("");

    product += `
  <div class="card">
    <div class="card-main">
        <div class="deal-badge">${buses[i].deal}</div>
      <div class="left">
        <div class="brand-row">
          <div class="brand">
            <span class="brand-name">${buses[i].operator}</span>
            <span class="brand-ico" aria-hidden="true">🚍</span>
          </div>
          <div>
          <div class="rating-pill" title="Rating">
            <span class="star">★</span>
            <span class="score">${buses[i].rating}</span>
          </div>

          <div class="count-pill">${buses[i].reviewsCount}</div>
          </div>

          <div class="time-price">
            <div class="times">
              <span class="time">${buses[i].depart}</span>
              <span class="dash">—</span>
              <span class="time">${buses[i].arrive}</span>
            </div>
            <div class="minor">
              <span>${buses[i].duration}</span>
              <span class="dot">·</span>
              <span>${buses[i].seatsTotal} (${buses[i].singleSeats} Single)</span>
            </div>
          </div>
          <div class="price-org">
            ₹${buses[i].originalPrice}
          </div>
          <div class="price-col">
            <div class="price">₹${buses[i].cutoffPrice}</div>
            <div class="onwards">${buses[i].priceNote}</div>
          </div>
        </div>

        <div class="sub-row">
          <div class="spec">${buses[i].vehicle}</div>
        </div>
      </div>
    </div>

    <div class="card-footer">
    <div>  
    <div class="left-foot">
        ${tagChips}
      </div>
      <div class="tag2">
       ${buses[i].tag2}
    </div>
    </div>
      <button class="cta">View seats</button>
    </div>
  </div>
</div>
`;

}
document.getElementById('text').innerHTML = product;


